public class classjan1 
{
    
 // public database.queryselector start(BatchableContext bc)
  //{
     // string query = [Select id, LastName from Contact];
      
      //return database.querylocator(query);
 // }
    
   // public static void execute(BatchableContext bc list<Contact> cc)
    //{
    //    for(Contact ac:cc)
     //   {
            
     //   }
  //  }
    
   // public static void finish(BatchableContext bc)
   // {
        
   // }
 
}